
version: 2
jobs:
  test:
    docker:
      - image: rhinogram/node-awscli

    working_directory: /tmp/area-c

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  build:
      - run: npm run build

  deploy:
      - run: aws s3 sync ./build s3://area-c-dev --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
